version: '2'

services:
  server:
    build: ./
    ports:
      - 8338:8338
      - 127.0.0.1:8337:8337/udp
    volumes:
      - ./maltrail.conf:/maltrail.conf:ro
      - ./logs:/var/log/maltrail
    command: python server.py
    logging:
      driver: json-file
    
  sensor:
    build: ./
    privileged: true
    network_mode: host
    volumes:
      - ./maltrail.conf:/maltrail.conf:ro
    command: python sensor.py
    logging:
      driver: json-file