version: '2.1'

services:
  server:
    build: ./
    ports:
      - 8338:8338
      - 127.0.0.1:8337:8337/udp
    volumes:
      - ./maltrail.conf:/maltrail.conf:ro
      - ./logs:/var/log/maltrail
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command: python server.py
    logging:
      driver: json-file
    restart: always
    healthcheck:
      test: bash -c "cat </dev/null >/dev/tcp/127.0.0.1/8338 && cat </dev/null >/dev/udp/127.0.0.1/8337"
    
  sensor:
    build: ./
    privileged: true
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - ./maltrail.conf:/maltrail.conf:ro
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    command: /maltrail/run-sensor.sh
    logging:
      driver: json-file
    restart: always
    healthcheck:
      test: bash -c '[[ $$(pgrep -fc sensor.py) -gt 1 ]]'